before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build_image:
  script:
    - docker build -t registry.gitlab.inria.fr/nvauquie/text_transformer .
    - docker push registry.gitlab.inria.fr/nvauquie/text_transformer
